language: node_js

node_js: 
  - 9
  - node

install:
  - npm install -g codecov
  - npm install -g coveralls
  - npm install -g nyc

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha

script:
  - "npm start &"
  - "nyc --reporter=lcov npm test"
  
after_success:
    - codecov
