language: node_js

node_js: 
  - 9
  - node

install: true

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha

script:
<<<<<<< HEAD
  - npm start 
=======
  - "npm start &"
>>>>>>> e4d76097ce80f78db722fef698bcd986eecc5fda
  - npm test
  - npm run coveralls
