language: node_js

node_js: 
  - 9
  - node

install:
  - npm install -g codecov
  - npm install -g coveralls

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - chmod 0777 ./node_modules/.bin/nyc

script:
  - "npm start &"
  - npm test
  
after_success:
    - codecov
