language: node_js

node_js: 
  - 9
  - node

install: true

before_script: 
  - chmod 0777 ./node_modules/.bin/mocha

script:
  - "npm start &"
  - npm test
  
after_success:
    - bash <(curl -s https://codecov.io/bash)
